### ISSUE TITLE
Icon size is smaller than original icon

### ISSUE THREAD

**Issue by Human7900** [ichelash/bigsur#2]
The two and one bar icons are smaller than the original icons included in Big Sur![Screen Shot 2021-05-15 at 11 27 48 PM](https://user-images.githubusercontent.com/84245065/118373588-601b5e80-b5d5-11eb-8d9d-2cd382ccd41a.png)

**Comment by ichelash** [comment]
Yeah...i noticed that..fixing that on the next release coming sooner

**Comment by Human7900** [comment]
Any idea when the update will come?

**Comment by ichelash** [comment]
Next week..probably Monday or Tuesday..try to fix dark and light mode into one bundle.

**Comment by Human7900** [comment]
> Next week..probably Monday or Tuesday..try to fix dark and light mode into one bundle.

That would be great!

**Comment by ichelash** [comment]
> > Next week..probably Monday or Tuesday..try to fix dark and light mode into one bundle.
> 
> That would be great!

Awesome

**Comment by ichelash** [comment]
> > Next week..probably Monday or Tuesday..try to fix dark and light mode into one bundle.
> 
> That would be great!

Try this and let me know of any issues https://github.com/ichelash/bigsur/releases/tag/v6

**Comment by Human7900** [comment]
> > > Next week..probably Monday or Tuesday..try to fix dark and light mode into one bundle.
> > 
> > 
> > That would be great!
> 
> Try this and let me know of any issues https://github.com/ichelash/bigsur/releases/tag/v6

Tried v7 but the 2 and 1 bar icons are still small

![Screen Shot 2021-05-16 at 11 06 56 AM](https://user-images.githubusercontent.com/84245065/118386681-dc925980-b636-11eb-905d-3287cb95fa9f.png)


Trying v6 now.

**Comment by Human7900** [comment]
> > > Next week..probably Monday or Tuesday..try to fix dark and light mode into one bundle.
> > 
> > 
> > That would be great!
> 
> Try this and let me know of any issues https://github.com/ichelash/bigsur/releases/tag/v6

Hey tried v6 but the 2 and 1 bar icon is lower and smaller than the original icon

![Screen Shot 2021-05-16 at 11 16 38 AM](https://user-images.githubusercontent.com/84245065/118386879-36475380-b638-11eb-9498-89c6dd87fc29.png)

(Don't know if it is visible in the screenshot)

**Comment by ichelash** [comment]
Try the v7

**Comment by Human7900** [comment]
> Try the v7 https://github.com/ichelash/bigsur/releases/tag/v7

The first screenshot I shared was from v7
 Can you increase a size little bit of v7 .Cause it looks the same as v5

**Comment by ichelash** [comment]
I think you have an issue..mine looks exactly 
![Screenshot 2021-05-16 at 14 25 19](https://user-images.githubusercontent.com/37507293/118395354-9f3bc500-b652-11eb-9faa-e03daa110af4.png)

**Comment by ichelash** [comment]
> > > > Next week..probably Monday or Tuesday..try to fix dark and light mode into one bundle.
> > > 
> > > 
> > > That would be great!
> > 
> > 
> > Try this and let me know of any issues https://github.com/ichelash/bigsur/releases/tag/v6
> 
> Hey tried v6 but the 2 and 1 bar icon is lower and smaller than the original icon
> 
> ![Screen Shot 2021-05-16 at 11 17 56 AM](https://user-images.githubusercontent.com/84245065/118386912-67c01f00-b638-11eb-8890-a41a834d8885.png)
> 
> (Don't know if it is visible in the screenshot)

This icons are the same.....

**Comment by Human7900** [comment]
Will I be possible to bundle both black and white icons to chang according to wallpaper.
I want to use dynamic walpapaper.
Thanks.

**Comment by Human7900** [comment]
> Not anytime soon.....you'll just change it manually..but working on it.

OK. Waiting for it.

**Comment by ichelash** [comment]
> > Not anytime soon.....you'll just change it manually..but working on it.
> 
> OK. Waiting for it.

Give it... 1 to 2 weeks..you'll get all in one icns..but how are the new icons?

**Comment by Human7900** [comment]
Way better! Maybe still a little smaller than the original icon :)

**Comment by ichelash** [comment]
> Way better! Maybe still a little smaller than the original icon :)

redownload the new v7..i re uploaded new icns.. after the release

**Comment by Human7900** [comment]
Redownloaded now. Looks good.

**Comment by Human7900** [comment]
Can you write  a comment here when you release auto-changing icons so that I get a notification.

**Comment by ichelash** [comment]
Sure

**Comment by Human7900** [comment]
Any update on auto changing icons? Can I help you in some way?

**Comment by ichelash** [comment]
Not yet..what kind of help?

**Comment by Human7900** [comment]
In helping you make the icons.

**Comment by Human7900** [comment]
What is the resolution of your icons?

**Comment by Human7900** [comment]
Any update on the auto changing icons? By the way, what is the resolution of the icons?

**Comment by ichelash** [comment]
> Any update on the auto changing icons? By the way, what is the resolution of the icons?

No update anytime soon, working on clients projects now.. 512x512

**Comment by Human7900** [comment]
Hi,
Any update?
